version: "3.9"

services:
  database_onecar:
    image: postgres
    container_name: database_onecar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=onecar
    volumes:
      - pgdata:/data/postgres

  mongo_onecar:
    image: mongo
    container_name: mongo_onecar
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    volumes:
      - pgdatamongo:/data/mongo

  app:
    build: .
    container_name: onecar
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_onecar
      - mongo_onecar
    depends_on:
      - database_onecar
      - mongo_onecar

volumes:
  pgdata:
    driver: local
  pgdatamongo:
    driver: local

