version: "3.9"

services:
  database_onecar:
    image: postgres
    container_name: database_onecar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=onecar
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: onecar
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_onecar
    depends_on:
      - database_onecar



volumes:
  pgdata:
    driver: local

